age = int(input("please tell me your age: "))
print(f"You") are currently {age} years old.)
print(f"In 10 years, you'11 be {age + 10} years old.")
print(f"In 20 years, you'11 be {age + 10} years old.")
print(f"In 10 years, you'11 be {age + 10} years old.")