A = int(input("Give me the first number : "))
B = int(input("Give me the second number : "))
Print("Thank you")
print(f"{A} + {B} = {A+b}")
print(f"{A} - {B} = {A-b}")
print(f"{A} * {B} = {A*b}")
print(f"{A} / {B} = {A/b}")